1. Principal Component Analysis


a. Apply PCA on CC dataset.


b. Apply k-means algorithm on the PCA result and report your observation if the silhouette score has
improved or not?


c. Perform Scaling+PCA+K-Means and report performance.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

from sklearn.linear_model import LinearRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.cluster import KMeans
from sklearn import metrics

from sklearn.preprocessing import StandardScaler
from sklearn import svm

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
data = pd.read_csv("/CC GENERAL.csv")
print(data.head())
data.isna().sum()


  CUST_ID      BALANCE  BALANCE_FREQUENCY  PURCHASES  ONEOFF_PURCHASES  \
0  C10001    40.900749           0.818182      95.40              0.00   
1  C10002  3202.467416           0.909091       0.00              0.00   
2  C10003  2495.148862           1.000000     773.17            773.17   
3  C10004  1666.670542           0.636364    1499.00           1499.00   
4  C10005   817.714335           1.000000      16.00             16.00   

   INSTALLMENTS_PURCHASES  CASH_ADVANCE  PURCHASES_FREQUENCY  \
0                    95.4      0.000000             0.166667   
1                     0.0   6442.945483             0.000000   
2                     0.0      0.000000             1.000000   
3                     0.0    205.788017             0.083333   
4                     0.0      0.000000             0.083333   

   ONEOFF_PURCHASES_FREQUENCY  PURCHASES_INSTALLMENTS_FREQUENCY  \
0                    0.000000                          0.083333   
1                    0.000000       

CUST_ID                               0
BALANCE                               0
BALANCE_FREQUENCY                     0
PURCHASES                             0
ONEOFF_PURCHASES                      0
INSTALLMENTS_PURCHASES                0
CASH_ADVANCE                          0
PURCHASES_FREQUENCY                   0
ONEOFF_PURCHASES_FREQUENCY            0
PURCHASES_INSTALLMENTS_FREQUENCY      0
CASH_ADVANCE_FREQUENCY                0
CASH_ADVANCE_TRX                      0
PURCHASES_TRX                         0
CREDIT_LIMIT                          1
PAYMENTS                              0
MINIMUM_PAYMENTS                    313
PRC_FULL_PAYMENT                      0
TENURE                                0
dtype: int64

In [ ]:
data['MINIMUM_PAYMENTS'].fillna(data['MINIMUM_PAYMENTS'].mean(), inplace=True)
data.dropna(axis=1,inplace=True)

In [ ]:
data.drop(['CUST_ID'], axis=1, inplace=True)

In [ ]:
kcluster = 3
knn = KMeans(n_clusters=kcluster)
knn.fit(data)
print(knn)
# predict the cluster for each data point
ycknn = knn.predict(data)
score = metrics.silhouette_score(data, ycknn)
print(score)

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=3)
0.5502197877782317


In [ ]:
### Using Principal Component Analysis
pca = PCA(2)
x_p = pca.fit_transform(data)
df_2 = pd.DataFrame(data=x_p)

In [ ]:
kcluster = 3
knn = KMeans(n_clusters=kcluster)
knn.fit(df_2)
print(knn)
# predict the cluster for each data point
ycknn = knn.predict(df_2)
score = metrics.silhouette_score(df_2, ycknn)
print(score)

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=3)
0.604019930174816


In [ ]:
sc = StandardScaler()
sc_data = sc.fit_transform(df_2)

In [ ]:
kcluster = 3
knn = KMeans(n_clusters=kcluster)
knn.fit(sc_data)
print(knn)
# predict the cluster for each data point
ycknn = knn.predict(sc_data)
score = metrics.silhouette_score(sc_data, ycknn)
print(score)

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=3)
0.6339379378657516


2. Use pd_speech_features.csv


a. Perform Scaling


b. Apply PCA (k=3)


c. Use SVM to report performance

In [ ]:
speech_data = pd.read_csv('/pd_speech_features.csv')
speech_data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Columns: 755 entries, id to class
dtypes: float64(749), int64(6)
memory usage: 4.4 MB


In [ ]:
speech_data['class'].value_counts()

1    564
0    192
Name: class, dtype: int64

In [ ]:
speech_data

id  gender      PPE      DFA     RPDE  numPulses  numPeriodsPulses  \
0      0       1  0.85247  0.71826  0.57227        240               239   
1      0       1  0.76686  0.69481  0.53966        234               233   
2      0       1  0.85083  0.67604  0.58982        232               231   
3      1       0  0.41121  0.79672  0.59257        178               177   
4      1       0  0.32790  0.79782  0.53028        236               235   
..   ...     ...      ...      ...      ...        ...               ...   
751  250       0  0.80903  0.56355  0.28385        417               416   
752  250       0  0.16084  0.56499  0.59194        415               413   
753  251       0  0.88389  0.72335  0.46815        381               380   
754  251       0  0.83782  0.74890  0.49823        340               339   
755  251       0  0.81304  0.76471  0.46374        340               339   

     meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...  \
0            0.008064            0.000087       0.00218  ...   
1            0.008258            0.000073       0.00195  ...   
2            0.008340            0.000060       0.00176  ...   
3            0.010858            0.000183       0.00419  ...   
4            0.008162            0.002669       0.00535  ...   
..                ...                 ...           ...  ...   
751          0.004627            0.000052       0.00064  ...   
752          0.004550            0.000220       0.00143  ...   
753          0.005069            0.000103       0.00076  ...   
754          0.005679            0.000055       0.00092  ...   
755          0.005676            0.000037       0.00078  ...   

     tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
0                       1.5620                     2.6445   
1                       1.5589                     3.6107   
2                       1.5643                     2.3308   
3                       3.7805                     3.5664   
4                       6.1727                     5.8416   
..                         ...                        ...   
751                     3.0706                     3.0190   
752                     1.9704                     1.7451   
753                    51.5607                    44.4641   
754                    19.1607                    12.8312   
755                    62.9927                    21.8152   

     tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
0                       3.8686                     4.2105   
1                      23.5155                    14.1962   
2                       9.4959                    10.7458   
3                       5.2558                    14.0403   
4                       6.0805                     5.7621   
..                         ...                        ...   
751                     3.1212                     2.4921   
752                     1.8277                     2.4976   
753                    26.1586                     6.3076   
754                     8.9434                     2.2044   
755                     9.2457                     4.8555   

     tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
0                       5.1221                     4.4625   
1                      11.0261                     9.5082   
2                      11.0177                     4.8066   
3                       4.2235                     4.6857   
4                       7.7817                    11.6891   
..                         ...                        ...   
751                     3.5844                     3.5400   
752                     5.2981                     4.2616   
753                     2.8601                     2.5361   
754                     1.9496                     1.9664   
755                     3.0551                     3.0415   

     tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
0                       2.6202                     3.0004   
1  

In [ ]:
X = speech_data.drop(['class'],axis=1)
y = speech_data['class']
X.columns

Index(['id', 'gender', 'PPE', 'DFA', 'RPDE', 'numPulses', 'numPeriodsPulses',
       'meanPeriodPulses', 'stdDevPeriodPulses', 'locPctJitter',
       ...
       'tqwt_kurtosisValue_dec_27', 'tqwt_kurtosisValue_dec_28',
       'tqwt_kurtosisValue_dec_29', 'tqwt_kurtosisValue_dec_30',
       'tqwt_kurtosisValue_dec_31', 'tqwt_kurtosisValue_dec_32',
       'tqwt_kurtosisValue_dec_33', 'tqwt_kurtosisValue_dec_34',
       'tqwt_kurtosisValue_dec_35', 'tqwt_kurtosisValue_dec_36'],
      dtype='object', length=754)

In [ ]:
pca = PCA(3)
x_pca = pca.fit_transform(X)
X2 = pd.DataFrame(data=x_pca)


In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25)


In [ ]:
clf = svm.SVC()
clf.fit(X_train, y_train)
clf.score(X_train,y_train)

0.9065255731922398

In [ ]:
y_pred = clf.predict(X_test)


In [ ]:
metrics.accuracy_score(y_test, y_pred)


0.8835978835978836

3. Apply Linear Discriminant Analysis (LDA) on Iris.csv dataset to reduce dimensionality of data tok=2.

In [ ]:
iris_data = pd.read_csv('/Iris.csv')

In [ ]:
X = iris_data[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = iris_data['Species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [ ]:
### Using Linear Discriminant Analysis

LDA = LinearDiscriminantAnalysis(n_components=2)
X_train = LDA.fit_transform(X_train, y_train)
X_test = LDA.transform(X_test)

In [ ]:
RF = RandomForestClassifier(max_depth=2, random_state=0)
RF.fit(X_train, y_train)
RF.score(X_train, y_train)

0.9910714285714286

In [ ]:
y_pred = RF.predict(X_test)
cf = confusion_matrix(y_test, y_pred)
print(cf)
print()
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))

[[10  0  0]
 [ 0 13  2]
 [ 0  1 12]]

Accuracy : 0.9210526315789473


Briefly identify the difference between PCA and LDA







PCA and LDA are both dimensionality reduction techniques used in machine learning.


PCA aims to find the most important features that capture the most variance in the data, while LDA aims to find a projection of the data that maximizes the separation between different classes in the data.


PCA is an unsupervised learning technique, meaning it does not consider the class labels of the data, while LDA is a supervised learning technique that takes into account the class labels of the data.


PCA creates new features by combining the original features in a way that maximizes the variance of the data along each new feature, while LDA creates new features by maximizing the ratio of between-class variance to within-class variance.


PCA is used for dimensionality reduction and feature extraction, while LDA is mainly used for classification.